### ISSUE TITLE
Modifier support live in V8

### ISSUE THREAD

**Issue by slevithan** [tc39/proposal-regexp-modifiers#15]
Support for regex modifiers is live as of May 14 in Chrome and Edge 125: [Chrome Platform Status](https://cr-status.appspot.com/feature/5100254548721664), [Chrome 125 Release Notes](https://developer.chrome.com/release-notes/125).

Should this status be added to the readme?

Congrats! I'm excited for this feature.

**Comment by rbuckton** [comment]
I'll look into updating the 
Readme tomorrow.
