### ISSUE TITLE
Stage 3 Specification Review: Richard Gibson

### ISSUE THREAD

**Issue by rbuckton** [tc39/proposal-regexp-modifiers#5]
This is a placeholder task for the Stage 3 Specification Review feedback from Richard Gibson (@gibson042).

**Comment by rbuckton** [comment]
@gibson042 have you had an opportunity to review the specification text?

**Comment by rbuckton** [comment]
FYI, I am considering bringing this to plenary in June for Stage 3, pending reviews.

**Comment by gibson042** [comment]
Overall, I think this is pretty close. Specific comments below, separated by horizontal lines.

----

> A <em>Modifiers</em> is an ordered triple (_dotAll_, _ignoreCase_, _multiline_) representing the current state of _DotAll_, _IgnoreCase_, and _Multiline_.

Tracking what data corresponds with a given tuple index is cumbersome... I think a Record like { [[dotAll]], [[ignoreCase]], [[multiline]] } would be more appropriate. I'm also not sure about "current state"—perhaps that would be better phrased as «…representing a combination of _DotAll_, _IgnoreCase_, and _Multiline_ behavior applicable to a pattern or subpattern»? That would result in replacing references like «_modifiers_'s _multiline_» with «_modifiers_.[[multiline]]», which I think improves both comprehension and readability.

----

> It is a Syntax Error if the source texts that were recognized as the first and second |RegularExpressionFlags| are both the empty string.

[Source text](https://tc39.es/ecma262/multipage/ecmascript-language-source-code.html#sec-ecmascript-language-source-code) is a sequence of code points, not a string. And there is a specific definition for [source text matched by](https://tc39.es/ecma262/multipage/notational-conventions.html#sec-algorithm-conventions-syntax-directed-operations) that I think should be used here.

```patch
         <emu-grammar>Atom :: `(` `?` RegularExpressionFlags `:` Disjunction `)`</emu-grammar>
         <ul>
-          <li>It is a Syntax Error if the source text that was recognized as |RegularExpressionFlags| contains any code point other than `i`, `m`, or `s`, or if it contains the same code point more than once.
+          <li>It is a Syntax Error if the source text matched by |RegularExpressionFlags| contains any code point other than `i`, `m`, or `s`, or if it contains the same code point more than once.
         </ul>
         <emu-grammar>Atom :: `(` `?` RegularExpressionFlags `-` RegularExpressionFlags `:` Disjunction `)`</emu-grammar>
         <ul>
-          <li>It is a Syntax Error if the source texts that were recognized as the first and second |RegularExpressionFlags| are both the empty string.
+          <li>It is a Syntax Error if the source text matched by the first |RegularExpressionFlags| and the source text matched by the second |RegularExpressionFlags| are both empty.
-          <li>It is a Syntax Error if the source text that was recognized as the first |RegularExpressionFlags| contains any code point other than `i`, `m`, or `s`, or if it contains the same code point more than once.
-          <li>It is a Syntax Error if the source text that was recognized as the second |RegularExpressionFlags| contains any code point other than `i`, `m`, or `s`, or if it contains the same code point more than once.
+          <li>It is a Syntax Error if the source text matched by either |RegularExpressionFlags| contains any code point other than `i`, `m`, or `s`, or 
+          <li>It is a Syntax Error if the source text matched by either |RegularExpressionFlags| contains more than one instance of any code point.
         </ul>
```

----

It looks like you missed an operation argument in CompileSubpattern.
```patch
         <emu-grammar>Term :: Assertion</emu-grammar>
         <emu-alg>
-          1. Return CompileAssertion of |Assertion|.
+          1. Return CompileAssertion of |Assertion| with argument _modifiers_.
         </emu-alg>
```

----

There's a typo in the structured header of CompileAtom (that probably should have been caught by ecmarkup, so I opened https://github.com/tc39/ecmarkup/issues/454 ).
```patch
           Runtime Semantics: CompileAtom (
             _direction_: ~forward~ or ~backward~,
-            <ins>_modifiers: a Modifiers,</ins>
+            <ins>_modifiers_: a Modifiers,</ins>
           ): a Matcher
```

----

There's more use of "recognized" rather than "matched by" and "string" rather than "sequence of code points" in CompileAtom, and (as a nit) the "add" and "remove" aliases are a bit generic.
```patch
         <emu-grammar>Atom :: `(` `?` RegularExpressionFlags `:` Disjunction `)`</emu-grammar>
         <emu-alg>
-          1. Let _add_ be the source text that was recognized as |RegularExpressionFlags|.
-          1. Let _remove_ be the empty String.
-          1. Let _newModifiers_ be UpdateModifiers(_modifiers_, _add_, _remove_).
+          1. Let _addModifiers_ be the source text matched by |RegularExpressionFlags|.
+          1. Let _removeModifiers_ be the empty String.
+          1. Let _newModifiers_ be UpdateModifiers(_modifiers_, CodePointsToString(_addModifiers_), _removeModifiers_).
           1. Return CompileSubpattern of |Disjunction| with arguments _direction_ and _newModifiers_.
         </emu-alg>
         <emu-grammar>Atom :: `(` `?` RegularExpressionFlags `-` RegularExpressionFlags `:` Disjunction `)`</emu-grammar>
         <emu-alg>
-          1. Let _add_ be the source text that was recognized as the first |RegularExpressionFlags|.
-          1. Let _remove_ be the source text that was recognized as the second |RegularExpressionFlags|.
-          1. Let _newModifiers_ be UpdateModifiers(_modifiers_, _add_, _remove_).
+          1. Let _addModifiers_ be the source text matched by the first |RegularExpressionFlags|.
+          1. Let _removeModifiers_ be the source text matched by the second |RegularExpressionFlags|.
+          1. Let _newModifiers_ be UpdateModifiers(_modifiers_, CodePointsToString(_addModifiers_), CodePointsToString(_removeModifiers_)).
           1. Return CompileSubpattern of |Disjunction| with arguments _direction_ and _newModifiers_.
         </emu-alg>
```

----

Editorial nit regarding GetWordCharacters.
```patch
         <emu-alg>
-          1. Let _wordCharacters_ be the mathematical set that is the union of all sixty-three characters in *"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_"* (letters, numbers, and U+005F (LOW LINE) in the Unicode Basic Latin block) and all characters _c_ for which _c_ is not in that set but Canonicalize(_c_, _modifiers_) is. _wordCharacters_ cannot contain more than sixty-three characters unless _Unicode_ and _modifiers_'s _ignoreCase_ are both *true*.
+          1. Let _wordCharacters_ be the mathematical set that is the union of all sixty-three characters in *"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_"* (letters, numbers, and U+005F (LOW LINE) in the Unicode Basic Latin block) and all characters _c_ for which _c_ is not in that set but Canonicalize(_c_, _modifiers_) is.
           1. Return _wordCharacters_.
         </emu-alg>
+        <emu-note>
+          <p> _wordCharacters_ cannot contain more than sixty-three characters unless _Unicode_ and ${_ignoreCase_} are both *true*</p>
+        </emu-note>
```

Also, the ambient reference to _Unicode_ and scoped reference to _ignoreCase_ strikes me as awkward... I wonder if it would be better to capture all modifiers regardless of whether or not they can be overridden.

**Comment by rbuckton** [comment]
> Tracking what data corresponds with a given tuple index is cumbersome... I think a Record like { [[dotAll]], [[ignoreCase]], [[multiline]] } would be more appropriate. [...] That would result in replacing references like «_modifiers_'s _multiline_» with «_modifiers_.[[multiline]]», which I think improves both comprehension and readability.

This is consistent with the rest of the RegExp specification text. For example:

> A _State_ is an ordered pair (_endIndex_, _captures_) where _endIndex_ is an [integer](https://tc39.es/ecma262/#integer) and _captures_ is a [List](https://tc39.es/ecma262/#sec-list-and-record-specification-type) of _NcapturingParens_ values.

However, every reference in the spec text still references a _State_'s _endIndex_ and _captures_ by name. This is something I'd defer to the editors, however, since this representation seems editorial in nature. In general I'm of the opinion that _Range_ and _State_ should also be represented as Records, but would rather not make that change in this proposal.

> [...] I'm also not sure about "current state"—perhaps that would be better phrased as «…representing a combination of _DotAll_, _IgnoreCase_, and _Multiline_ behavior applicable to a pattern or subpattern»? 

I'll work on the wording here, thanks!

> Also, the ambient reference to _Unicode_ and scoped reference to _ignoreCase_ strikes me as awkward... I wonder if it would be better to capture all modifiers regardless of whether or not they can be overridden.

I don't disagree, but I'm not 100% sure I should make that change here. I'm concerned it could be construed as potentially allowing flags like _Unicode_ to be changed in the future. This also feels like a question for the TC39 editors.

**Comment by rbuckton** [comment]
> ```diff
> -          <li>It is a Syntax Error if the source text that was recognized as the first |RegularExpressionFlags| contains any code point other than `i`, `m`, or `s`, or if it contains the same code point more than once.
> -          <li>It is a Syntax Error if the source text that was recognized as the second |RegularExpressionFlags| contains any code point other than `i`, `m`, or `s`, or if it contains the same code point more than once.
> +          <li>It is a Syntax Error if the source text matched by either |RegularExpressionFlags| contains any code point other than `i`, `m`, or `s`, or 
> +          <li>It is a Syntax Error if the source text matched by either |RegularExpressionFlags| contains more than one instance of any code point.
>          </ul>
> ```

I'm a bit worried about the wording in the last line, since it could possibly be construed as disallowing `(?i-i:.)`, which is still an open question in #8.

**Comment by rbuckton** [comment]
I've applied the proposed changes in #10. I also switched `Modifiers` from an ordered triple to a Record.
