### ISSUE TITLE
Behavior for backreferences

### ISSUE THREAD

**Issue by bakkot** [tc39/proposal-regexp-modifiers#7]
I can read this off of the spec text, probably, but just to confirm:

What is the intended behavior for backreferences where the captured group has a different `ignoreCase` state than the backreference itself? (In both directions.) And how does the proposed behavior compare to other languages?

**Comment by rbuckton** [comment]
The exact text of the capture group referenced by the backreference is matched using the *current* setting for `ignoreCase`, per [BackreferenceMatcher](https://tc39.es/proposal-regexp-modifiers/#sec-backreference-matcher). I've checked this against Perl and .NET, which have the same behavior:

| Pattern               | Input  | Perl  | .NET  | Proposal |
|:----------------------|:------:|:-----:|:-----:|:--------:|
| `/(?i:(a))\1/`        | `"AA"` |  ✅  |  ✅  |    ✅     |
| `/(?i:(a))\1/`        | `"Aa"` |  ⛔  |  ⛔  |    ⛔     |
| `/((?i:a))\1/`        | `"AA"` |  ✅  |  ✅  |    ✅     |
| `/((?i:a))\1/`        | `"Aa"` |  ⛔  |  ⛔  |    ⛔     |
| `/(?i:(a))(?i:\1)/`   | `"AA"` |  ✅  |  ✅  |    ✅     |
| `/(?i:(a))(?i:\1)/`   | `"Aa"` |  ✅  |  ✅  |    ✅     |
| `/(?-i:(A))\1/i`      | `"AA"` |  ✅  |  ✅  |    ✅     |
| `/(?-i:(A))\1/i`      | `"Aa"` |  ✅  |  ✅  |    ✅     |

**Comment by rbuckton** [comment]
@bakkot was this answer satisfactory?

**Comment by bakkot** [comment]
Yup, thanks for compiling that table.
