### ISSUE TITLE
Is it legal to both enable and disable a flag, as in `(?i-i:.)`?

### ISSUE THREAD

**Issue by bakkot** [tc39/proposal-regexp-modifiers#8]
That seems potentially fraught; it's not obvious which should take precedence.

**Comment by rbuckton** [comment]
Precedent in other languages seems to be: 
1. Modifiers before `-` are added, then
2. Modifiers after `-` are removed.

Which means `(?i-i:.)` is equivalent to `(?-i:.)`, which is what the spec text should currently reflect.

**Comment by bakkot** [comment]
Is there a reason to want this to be legal, other than precedent from other languages?

**Comment by ljharb** [comment]
I’d expect this to be syntactically prevented, since it’s confusing as to whether the two cancel out, or whether i is already there and it’s a -i, or whether it’s not already there and it’s a noop.

**Comment by rbuckton** [comment]
@waldemarhorwat asked about this during the [December 2021 Plenary](https://github.com/tc39/notes/blob/main/meetings/2021-12/dec-15.md). My response was the same, and I have since verified the behavior in other engines. I had assumed consensus had already been reached on the behavior of `(?i-i:.)` at that time.

**Comment by bakkot** [comment]
The extent of the discussion in the notes is

> WH: And if it's the same flag on both sides of the `-`?
> 
> RBN: I would have check. That's either an error or a no op right now, I believe what the current specification text that I've written has is that it would first set the flag and then unset the flag, so it's essentially unsetting it. But again, I'll have to clarify that.

which I at least did not understand as the committee agreeing to permitting this.

**Comment by rbuckton** [comment]
I can add it to the slides for discussion in June. I would be fine with making it an error if necessary, it just seems needlessly pedantic.
